### PR TITLE
adding data for 2019, 2020

### PR DESCRIPTION
**Pull request by jayasurian123**
hi,
I have come across this npm module and found it useful. But it was missing 2019, 2020 data. So I have added it. 
I have also got the data for test cases. 

could you please check and if all good create a new npm version? 

regards
jay

### CODE REVIEW

**Comment by drinchev** [comment]
Hey @jayasurian123 . 

Thanks for your awesome PR :) 

I will try to release the package today / tomorrow with the updates.

**Comment by jayasurian123** [comment]
@drinchev kool thanks :)

**Comment by drinchev** [comment]
@jayasurian123 package was released :)

**Comment by froblesmartin** [comment]
Hi @drinchev! May you have a look at my comment on your blog? http://disq.us/p/2nam49k (https://www.drinchev.com/blog/germany-freelancing-and-taxes/)

**Comment by drinchev** [comment]
Hey @froblesmartin, 

Unfortunately the blog doesn't get as much love as I would love to at the moment. I'm quite busy with other stuff. I encourage you to use the library from here and make your own tool ;)

Best,
Ivan

**Pull request merged**
